# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: frame.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'frame.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66rame.proto\"%\n\x05\x46rame\x12\r\n\x05shape\x18\x01 \x03(\x05\x12\r\n\x05\x66rame\x18\x02 \x01(\x0c\x32/\n\x0f\x41nalyzerService\x12\x1c\n\nDeidentify\x12\x06.Frame\x1a\x06.Frameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frame_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAME']._serialized_start=15
  _globals['_FRAME']._serialized_end=52
  _globals['_ANALYZERSERVICE']._serialized_start=54
  _globals['_ANALYZERSERVICE']._serialized_end=101
# @@protoc_insertion_point(module_scope)
